### ISSUE TITLE
Structure of the Vehicles Page

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#100]
Once the Menu, Full Ownership and Elected Ownership Views are created, this task will connect each view with buttons and breadcrumbs (allow going back in pages).

**Comment by dAninAd1248** [comment]
Done. Branch is https://github.com/uprm-inso4116-2024-2025-s1/RUMBus-Dashboard/tree/vehicles-page-structure. Will do pull request tomorrow.

**Comment by gabrielpadilla7** [comment]
Great Job! Once the PR is made and merged, issue will be closed

**Comment by dAninAd1248** [comment]
@warm007 rebased the linked branch and already submitted a pull request.

**Comment by Yahid1** [comment]
Ok understand
