### ISSUE TITLE
Refresh Vehicles Page Design

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#102]
Refreshing of the implemented vehicles design. Add new buttons and colors to simplify the UI.

**Comment by diegorobles2** [comment]
We added tooltips to the vehicle and devices page, new buttons and highlighted the vehicles owned by UPRM. The work is under the Vehicle Design branch

**Comment by gabrielpadilla7** [comment]
Do you have a pull request to merge your code into main? Once I manage to merge it, this issue will be closed

**Comment by diegorobles2** [comment]
Added the pull request

**Comment by gabrielpadilla7** [comment]
@diegorobles2 approved the PR. Please resolve merge conflicts, after that the code can be merged. Once merged, I'll close this issue. Thank you!
