### ISSUE TITLE
Division of Tasks to Implement Revised Design

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#103]
After the "Revise Vehicles Page Design" is done, create tasks to implement the new design in the Vehicles Page.

**Comment by AngelMartinez33** [comment]
This is not necessary.

**Comment by Janiel777** [comment]
⚠️ **AngelMartinez33** intentó cerrar el issue, pero no tiene permisos para hacerlo. El issue ha sido reabierto.
