### ISSUE TITLE
[Documentation] Updating Terminology of seccion 2.1.5 in the documentation

### ISSUE THREAD

**Issue by JaseyAcevedo** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#106]
The terminology and ubiquitous language surrounding the domain is important to simplify communication about the domain. With this objective in mind section 2.1.5 of the documentation will be reviewed for possible opportunities to use the terminology already documented to simplify and prevent confusion.

**Comment by gabrielpadilla7** [comment]
This task does not count as an LTT, this is a documentation modification task

**Comment by gabrielpadilla7** [comment]
Finished, closing issue
