### ISSUE TITLE
[Lecture Topic Task] Use the Trolley: Reducing ignorance

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#107]
In order to understand why the RUMBus app is needed in the first place, it is important to be in the shoes of the user. This lecture topic task consisted of using the Trolley system ourselves and documenting the experience, with the purpose of knowing more what is the problem that we are trying to solve.

**Comment by gabrielpadilla7** [comment]
Closing as completed
