### ISSUE TITLE
Create a graphic that details documentation for milestone #2

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#111]
This task involves creating guide graphic that details how to implement changes to the milestone #1 documentation so that it is ready for submission.

**Comment by AngelMartinez33** [comment]
![Image](https://github.com/user-attachments/assets/5f62b9c7-1c71-4f6f-ae70-50686c4ad9ed)

**Comment by gabrielpadilla7** [comment]
Closing as completed
