### ISSUE TITLE
[Documentation] Revise 1.2.1 Current Situation and Fix 1.2.2 Needs -  Professor Feedback Milestone 1

### ISSUE THREAD

**Issue by warm007** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#117]
Professor Feedback:

The page about the trolley service at UPRM is from 2010 and it's just a rant that someone had. **You can cite it, but you'd have to make sure to put it into context.** Do not make it appear as if it was some kind of authoritative source.

"Students need notifications of any possible delays, service interruptions or route changes." this is a duplicate of some needs you already stated previously.

"Students need a way to track multiple trolleys at once to plan their schedules better." maybe better say something like students need a way to plan journeys spanning several routes.

"Students need easy access to all of this information through a user-friendly platform on their mobile devices." They definitely do not: students couldn't care less if they get the information on their mobile device or whether they would get this information by some other means.

I think you should revisit the needs and consolidate some of them. Also, strip them of any incidentals that come from your intention to implement this as a system/mobile app.

**Comment by warm007** [comment]
1.2.1 Current Situation: (Adding citations to web pages and putting text into context) 
In the UPRM, there exists various methods of transport to take the students to the locations they want to go (walking, cycling, automobiles, etc.). Among others, there's the trolley, a group of busses with higher capacity than other modes of transportation, but these have the issue that they are hard to locate due to there not being an easy way to know which routes they'll be talking at any given time, leading to very few people actually using them, this isn't a problem specific to the Trolleys in the UPRM either, even Bayamón and Carolina can't reach 5% use rates; Carolina's been measured to manage around 2% of it's population of 176,762, while Bayamón 0.5% of it's population of 201,600 (“Puerto Rico: Trolleys: Transportación Pública Urbana Y...” SkyscraperCity Forum, 7 Apr. 2014, [www.skyscrapercity.com/threads/puerto-rico-trolleys-transportaci%C3%B3n-p%C3%BAblica-urbana-y-rural.1484037/](http://www.skyscrapercity.com/threads/puerto-rico-trolleys-transportaci%C3%B3n-p%C3%BAblica-urbana-y-rural.1484037/)). Not only this, but they have their issues such as “it's slow, and never gets there on time. The trolley will get you to your destination, but about 30 minutes late.” (“The UPRM Trolley Is Just like the University, Frustrating.” The Colegio Blogporter, 14 Oct. 2010, https://engl3268.wordpress.com/2010/10/07/the-uprm-trolley-is-just-like-the-university-frustrating/) This affects so much the students as it does any faculty members that work at the Colegio (professors, janitors, support, etc.). Not just this, but there doesn't exist any solid way to monitor the trolleys to make sure their functioning at full capacity without risk of failure and the various other frustrations they give to their users.

1.2.2 Needs: (Fix )
•	**Real-Time Service Information:** Students require timely and accurate information on trolley locations, routes, and service availability to make informed travel decisions and minimize wait times.

•	**Optimized Journey Planning:** Students need a way to view and compare the most convenient trolley stops, as well as track multiple trolleys at once. This will enable them to choose the best boarding location and create more efficient schedules based on the timing and location of different trolleys.

•	**Convenient Access to Information:** Students and faculty need easy access to all relevant transportation information in a user-friendly and convenient format, enabling quick consultation without unnecessary complexity.

•	**Notifications and Alerts:** The ability to receive alerts for potential delays, route changes, or service interruptions is crucial for students to avoid missed appointments and manage time effectively.

•	**System Reliability:** Reliable service is essential, including operational hours and service availability across different days, such as regular weekdays, weekends, and holidays, ensuring there are no unexpected interruptions.

•	**Cross-Campus Ownership Accessibility:** Students from other campuses or institutions with their own in-campus trolley systems require similar access to reliable information. This includes real-time tracking, route planning, and service alerts, allowing each institution to customize and manage their own transportation system effectively within the same platform.

**Comment by gabrielpadilla7** [comment]
@warm007 has this been put into the  milestone 2 document? If you haven't, make sure to add it there, and make sure to follow the guidelines. 

As a reminder: here are the guidelines: 

![Image](https://github.com/user-attachments/assets/e9161b3c-36cc-464e-aa3c-82e2b04d1e16)

**Comment by warm007** [comment]
Greetings! I was waiting for review and approval before uploading it to the documentation. Now it is up in the Milestone Document #2.

**Comment by gabrielpadilla7** [comment]
Closing as completed!
