### ISSUE TITLE
[Lecture Topic Task] Comparing Smart UI Approach with Layered Architecture for the Trolley Tracker App

### ISSUE THREAD

**Issue by JoelTorres20** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#118]
Evaluate whether a smart UI or layered architecture is more suitable for the trolley tracker app. What are the trade-offs of using a simpler UI-based solution versus a layered architecture with isolated business logic?

**Comment by JoelTorres20** [comment]
### Comparing Smart UI Approach with Layered Architecture for the Trolley Tracker App

In software development, selecting the appropriate architectural pattern is critical to a project's long-term success. The choice between Smart UI and Layered Architecture for the Trolley Tracker App requires weighing the benefits and drawbacks of simplicity, development speed, scalability, and maintainability.

#### **Smart UI Approach:**

- **Concept**: The Smart UI approach involves concentrating most of the logic in the user interface (UI). It handles business logic, user interactions, and data fetching directly within the UI components.
- **Advantages**:
    - **Faster Development**: The UI manages logic, making development simpler since there is no need to create separate layers for business logic or data management.
    - **Less Complexity**: Developers can handle most operations in one place, resulting in fewer abstractions and faster changes.
- **Disadvantages**:
    - **Poor Scalability**: As the app grows (e.g., expanding to new campuses or adding features), maintaining the logic within the UI becomes difficult. The code can quickly become bloated and harder to manage.
    - **Low Maintainability**: Mixing business logic with UI makes the codebase fragile. Any change to the UI may impact core business logic, increasing the chances of introducing bugs.
    - **Difficult Testing**: Testing becomes harder since UI testing often requires visual validation, and the mixed logic can lead to hard-to-diagnose issues.

#### **Layered Architecture:**

- **Concept**: A layered architecture separates concerns into distinct layers: Presentation (UI), Application, Domain, and Infrastructure. Each layer focuses on a specific aspect of the application.
- **Advantages**:
    - **Scalability**: With clear separation between UI, business logic, and data management, the system can easily handle the addition of new features, campuses, or integrations with external services.
    - **Maintainability**: Isolating the business logic in the domain layer ensures that changes to the UI won’t affect core functionality. This results in a more maintainable codebase, even as the app grows.
    - **Ease of Testing**: Each layer can be tested independently. The business logic can be tested without UI involvement, and the UI can focus solely on presentation without worrying about backend logic.
- **Disadvantages**:
    - **More Complex Development**: Initial setup takes more time and requires careful design. Developers need to understand the flow of data across multiple layers, which can increase development time in the early stages.
    - **Learning Curve**: Developers unfamiliar with layered architecture might find it challenging to implement, especially in smaller teams where resources are limited.

#### **Analysis for Trolley Tracker App:**

The Trolley Tracker App is designed to manage real-time trolley tracking, route optimization, and notifications, with future plans for expansion to other campuses and integration with public transportation. Given this scope, a **Layered Architecture** is the better choice for the following reasons:
- **Scalability**: The app is expected to handle multiple campuses and possible expansions. A layered approach ensures that new features (e.g., different trolleys or routes) can be added without reworking the entire system.
- **Complexity of Business Logic**: Features like route planning, real-time GPS tracking, and notifications are not trivial. A layered approach isolates the business logic, ensuring that complex operations are handled properly and are easier to maintain.
- **Long-Term Maintenance**: Since the app will be used by different campuses and potentially many users, maintainability is key. With a Smart UI, future changes could break the entire system. In contrast, a layered architecture allows you to modify one layer (e.g., the domain or data) without affecting the others.

**Comment by gabrielpadilla7** [comment]
This looks good! Make sure to add it into the MIlestone 2 documentation in its appropiate section. For reference, here is the documentation: https://docs.google.com/document/d/1OOrI69c8hDkEQW57znoH-O1HwI0jaCxq8shAvwVBsog/edit#heading=h.9g5bln7fyk3c

Make sure to follow the guidelines for editing (and make sure to log it in section 5) . For reference:

![Image](https://github.com/user-attachments/assets/14df9f86-8090-4439-9b80-fde5b67aa0c4)

**Comment by JoelTorres20** [comment]
Just added it to the doc.

**Comment by gabrielpadilla7** [comment]
Closing as completed
