### ISSUE TITLE
Modify paragraph revision tasks

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#122]
Modify the paragraph revision tasks description to include the changes needed to the documentation. Right now it is divided in paragraphs, however the professor did not write paragraphs. Most of the writing is divided into lines with occasional paragraphs. 

This is to facilitate the process of documentation revision and to clear up doubts the developers might have when figuring out which parts they need to modify.

**Comment by Yahid1** [comment]
Create a Doc that indicates the division of tasks from the professors review. This includes changing the different tasks that tackle this situation and create other tasks pertaining the necessary tasks.

**Comment by Yahid1** [comment]
These task should be disclosed by the different number section and include all the comments made by the proffesor that critiques that part of the documentation.
