### ISSUE TITLE
[Documentation] Revise documentation section 1.4 and 2.1

### ISSUE THREAD

**Issue by dylanDeJesus21** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#123]
-Integrate section 1.4 throughout the documentation and eliminate it from being a separate section

-Give each domain entity and function a more thourough description, for example, what is the relationship between the location and the passengers? Or, what does a location entail? What does getBusLocation do?

**Comment by Yahid1** [comment]
Good Job
