### ISSUE TITLE
[Lecture Topic Task] Second order ignorance

### ISSUE THREAD

**Issue by dAninAd1248** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#125]
Professor feedback:
Where would you suspect that second order ignorance might be found?

Identify and detail aspects of our process which give way to second order of ignorance, where one is not aware of what one doesn't know.

**Comment by Janiel777** [comment]
⚠️ **dAninAd1248** intentó cerrar el issue, pero no tiene permisos para hacerlo. El issue ha sido reabierto.

**Comment by Janiel777** [comment]
⚠️ El usuario **Janiel777** reabrió el issue, pero no tiene permisos. Notificando a @gabrielpadilla7 @Yahid1.
