### ISSUE TITLE
[Documentation] Fix section 4.3 AND an Additional Comment on Professor's Feedback

### ISSUE THREAD

**Issue by JConcepcion01** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#134]
Address notes made by the professor on the Documentation. (To see details please refer to https://docs.google.com/document/d/16p2y0RkGJxVkwghhAxOAMc4ha6S6yq78j05DzVpHf8s/edit?usp=sharing)

**Comment by yamayrie** [comment]
Added description:

1. UI Layer
- Trolley Tracker Nav: This handles user interactions, allowing users to request information about the nearest trolley.
2. Application Layer
- Routes and Trolleys: Acts as the intermediary between the UI and Domain layers. This processes user requests and coordinates responses.
3. Domain Layer
- A123: User: Represents the user requesting trolley information.
- Google Maps: Utilizes mapping services to provide location-based data.
4. Structure Layer
- Database: Stores and retrieves data about trolley locations.

Interactions
- UI to Application: The UI layer calls getNearestTrolley(a123) from Trolley Tracker Nav to Routes and Trolleys.
- Application to Domain: Routes and Trolleys invokes tracking() in A123: User.
- Domain Interaction: A123: User calls getLocation() on Google Maps.
- Domain to Structure: Google Maps requests userLocation(a123) from the Database.
- Structure to Domain: The Database responds with trolleyLocation() back to Google Maps.
- Domain to UI: Google Maps sends display() back to A123: User, which then updates the UI.

**Comment by gabrielpadilla7** [comment]
closing as completed
