### ISSUE TITLE
[Lecture Topic Task] Identify aggregates and their relation

### ISSUE THREAD

**Issue by SebastianSaliva** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#136]
This task involves analyzing domain concepts and figuring out how to apply the concept of aggregates to them, and creating a graph to represent the aggregates

> **some guidelines**
> – cluster entities and value objects into aggregates
> – define boundaries around each
> – choose one entity as the root of each aggregate
> – control all access to objects inside the aggregate through the root
> – allow external references only to the root

**Comment by Yahid1** [comment]
Looks good.
