### ISSUE TITLE
[Lecture Topic Task] Update Orders of Ignorance

### ISSUE THREAD

**Issue by JaseyAcevedo** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#143]
There's been some new and old information that hasn't been documented in the first and second Orders of ignorance this task aims to update our documentation of these instances.

**Comment by JaseyAcevedo** [comment]
work done in section 4.2.5 of documentation.

**Comment by Yahid1** [comment]
Good job understanding.
