### ISSUE TITLE
[Lecture Topic Task] Maintaining Model Integrity: Bounded Contexts

### ISSUE THREAD

**Issue by AlexisTraversoPR** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#146]
Add a new section on Maintaining Model Integrity to the Trolley Tracker documentation, focusing on the use of Bounded Contexts to ensure model consistency and scalability. The section should explain how bounded contexts are applied (e.g., Real-Time Tracking, Route Planning, Admin Dashboard) and include guidelines for maintaining them.

**Comment by AlexisTraversoPR** [comment]
Added section 4.17

**Comment by gabrielpadilla7** [comment]
Please log your changes in the section 5 changelog so I can close this issue. Thank you!

**Comment by AlexisTraversoPR** [comment]
Logged changes in section 5, moving to in review

**Comment by gabrielpadilla7** [comment]
closing as completed
