### ISSUE TITLE
[Lecture Topic Task] Apply Levels of Ignorance to RUMBus Dashboard Development

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#147]
***Description:*** In this task, I will apply the concept of ```"levels of ignorance"``` to the RUMBus Dashboard project. While other team members have discussed and referenced aspects of this topic, I will delve further by detailing the influence of each level of ignorance on our notification system's design and implementation. This approach will help anticipate and mitigate potential knowledge gaps and improve our system's reliability under real-world conditions.

***Reference:*** The framework for levels of ignorance is based on the document titled ```"Effective Domain Modeling"```[(PDF reference)](https://github.com/user-attachments/files/17527412/003-EffectiveDomainModeling.1.pdf), which provides a structured way to identify and address various types of ignorance in the context of complex system development.

***Objective:*** The objective is to systematically analyze and address these ignorance levels to ensure a robust notification system for RUMBus, specifically tailored to handle dynamic operational environments with greater resilience.

**Comment by Janiel777** [comment]
***Applying Levels of Ignorance to the RUMBus Dashboard Project***

The development of the RUMBus Dashboard—a system for implementing notifications regarding the data from trolley sensors, such as speed, location, and fuel level—encounters various "levels of ignorance" that influence the design and implementation process. This report details how each level of ignorance may manifest within this project, impacting design considerations and development processes.

1. Zero-Order Ignorance (0OI) - Absence of Ignorance
At the initial phase of development, the team has a clear understanding of the system requirements: notifications must reliably display real-time data on speed, fuel level, and location of each trolley. This knowledge is concrete and measurable, as the team is aware of the core functionalities expected in the final dashboard. Here, the absence of ignorance allows the team to structure these features with confidence, establishing that notifications should be prompt and accurate for operational reliability.

2. First-Order Ignorance (1OI) - Lack of Knowledge
During development, the team may recognize certain uncertainties, such as the optimal frequency for updating notifications to balance real-time accuracy with system performance. Acknowledging this gap, the team may research various methods, including alternative architectures, or conduct load testing to determine the ideal update interval. This recognized lack of knowledge is critical, prompting active problem-solving and driving decisions that will enhance performance while avoiding resource strain on the dashboard.

3. Second-Order Ignorance (2OI) - Lack of Awareness
In this phase, the team may be unaware of unforeseen limitations, such as potential delays in sensor data transmission due to network connectivity issues with the trolleys. This lack of awareness could lead the developers to assume that all data will consistently reach the dashboard in real time. If this assumption remains unchallenged, it could lead to inaccuracies in the notification system when transmission delays occur. This level of ignorance underscores the need for developers to account for and mitigate real-world conditions that may disrupt seamless data flow, ensuring reliability in varying operational environments.

4. Third-Order Ignorance (3OI) - Lack of Process
Third-order ignorance appears if the team lacks a method for identifying network-related delays or evaluating their impact on notification accuracy. Without a process to uncover these limitations, the system might face unaddressed reliability issues in real-world deployments. To mitigate this, the team could perform simulated tests under different network conditions or observe operational data in a live environment, allowing them to identify and adapt to these scenarios. Developing such processes transforms unknowns into knowns, refining the dashboard's capabilities and reliability.

5. Fourth-Order Ignorance (4OI) - Meta Ignorance
Fourth-order ignorance relates to the team's lack of awareness about the existence of these levels of ignorance. If the team does not acknowledge potential blind spots, such as unknown limitations within sensor hardware or real-world operational factors, they may miss critical factors that influence system performance. In this case, unfamiliarity with the levels of ignorance could result in overlooked aspects, such as the need for regular updates or user feedback cycles, both of which are essential in recognizing latent issues.

Summary
In developing the RUMBus Dashboard, understanding and addressing each level of ignorance is essential to creating a robust notification system. By moving through these levels and actively managing identified gaps, the team can create a solution that not only meets immediate project requirements but also anticipates and mitigates potential future issues in real-world deployment. This awareness enables proactive improvements in system design, ensuring a high-performing dashboard tailored to dynamic operational conditions.

**Comment by Janiel777** [comment]
I added this in section ```4.2.4``` as concrete examples of these levels of ignorance related to our project since in the documentation I only saw definitions.

**Comment by Janiel777** [comment]
I highlighted what I added in green and also reported it in the Changelog table.

**Comment by Yahid1** [comment]
Looks good
