### ISSUE TITLE
[Lecture Topic Task] Explicit constraints

### ISSUE THREAD

**Issue by dylanDeJesus21** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#148]
In our Trolley Tracker app, we’ll implement explicit constraints to ensure data integrity and reliable operations. These constraints will define valid states for key elements, such as trolley capacity, acceptable stop intervals, and status checks. By enforcing these rules in our Angular services and methods, we can prevent invalid entries or conditions from disrupting the app’s functionality, making it more resilient and easier to maintain. This approach leverages TypeScript’s strict typing to add another layer of validation, ensuring our app operates within defined, reliable parameters.

**Comment by Yahid1** [comment]
Good enough
