### ISSUE TITLE
[Lecture Topic Task] Adding More Aggregates #2

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#151]
Aggregates pertaining the Dashboard objects and tabs.

**Comment by Yahid1** [comment]
![Image](https://github.com/user-attachments/assets/5581671b-2846-4796-80e3-935a4ca4b902)
Found this example by looking at the code.

**Comment by gabrielpadilla7** [comment]
closing as completed
