### ISSUE TITLE
Add user detection functionality to vheicle menu

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#155]
Set up the vehicle menu so that it can detect the name of the user and greet them with said name.

**Comment by MrL9000** [comment]
Updated the Vehicles tab to show the user's Username, found in the pull request at https://github.com/uprm-inso4116-2024-2025-s1/RUMBus-Dashboard/pull/37

![Image](https://github.com/user-attachments/assets/81e52b08-ceb0-4624-97b5-fb63cdffeddd)

**Comment by Yahid1** [comment]
Looks very good.

**Comment by Yahid1** [comment]
I will close this issue and merge it when necessary.
