### ISSUE TITLE
[Lecture Topic Task] Add Design Patterns for Consistency Section to Documentation

### ISSUE THREAD

**Issue by IvanierB** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#161]
Objective: Add a section introducing design patterns that support data consistency within the trolley tracker system, specifically focusing on the Observer and Singleton patterns.

Task Steps:

1. Briefly describe the importance of consistency across distributed components within the system.
2. Explain the Observer pattern, providing a use case for how it could keep notifications in sync with real-time trolley updates.
3. Describe the Singleton pattern and its potential use for maintaining a single source of truth across the application.
4. Conclude with a discussion on how these patterns enhance system reliability and reduce the risk of conflicting data.

**Comment by IvanierB** [comment]
Done under 4.16 section 2

**Comment by gabrielpadilla7** [comment]
closing as completed
