### ISSUE TITLE
Section 2.1.2: Terminology 

### ISSUE THREAD

**Issue by Brandell13** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#163]
Follows the guidelines on the content of a terminology.

**Comment by Brandell13** [comment]
2.1.2) Terminology
To ensure a clear and accurate understanding of the domain of our trolley tracking project, we define key terms below, highlighting their relationships and distinguishing characteristics in the context of the system:
* Trolley: A transportation vehicle used on campus to transport students and staff. Each trolley has a limited seating capacity and standing room. It is staffed by a designated driver, except in emergency situations where it may operate without passengers.
* Passenger: An individual who uses the trolley service, including both students and campus staff. Passengers follow safety rules, such as not occupying the driver's seat and not exceeding the trolley's maximum capacity.
* Driver: A person authorized to operate a trolley. Only one driver is assigned to an operating trolley, and their role is essential to the safe completion of routes. Drivers do not count as passengers and have additional responsibilities, such as reporting service problems.
* Route: A predetermined sequence of stops that each trolley transits. Routes are organized to optimize mobility on campus, allowing each stop to connect to key points. A route can be described as a list of stops in a specific order, with the possibility of defining intermediate points important for service efficiency.
* Stop: Specific location on campus where passengers can board or disembark from trolleys. Each stop can belong to multiple routes and has its own characteristics, such as peak times, which influence the frequency of service.
* Location: Geographic point of a trolley at a given time. In the context of the system, the location of a trolley allows users to track its progress in real time and estimate its arrival time at stops.
* Notification: Message sent to users to inform them of changes in service, such as delays, interruptions or route modifications. Notifications are a key component for user-system interaction and seek to improve the user experience by providing relevant information in real time.
* Tracking System: Set of tools and processes that allow monitoring and updating the location of trolleys in real time. This system is designed to provide accurate data and improve coordination between routes and stops.

**Comment by Brandell13** [comment]
Task completed

**Comment by gabrielpadilla7** [comment]
closing as completed
