### ISSUE TITLE
[Lecture Topic Task] Add Section on Performance Optimization Strategies

### ISSUE THREAD

**Issue by IvanierB** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#165]
Objective: Add a section detailing potential performance optimization strategies, particularly for data handling, API calls, and real-time updates.

Task Steps:

1. Explain general principles of performance optimization and why they are crucial in the context of real-time applications.
2. Identify specific areas in the trolley tracker system that may benefit from optimization, such as data caching, API rate limiting, or query optimization.
3. Provide examples of performance optimization methods, including lazy loading, data compression, and efficient data structures.
4. Summarize the importance of performance testing, profiling, and continuous monitoring to ensure sustained application responsiveness.

**Comment by IvanierB** [comment]
Done under section 5.18

**Comment by Yahid1** [comment]
You are missing how this was implemented. Giving Examples. Task will be closed but points will be reduced.
