### ISSUE TITLE
[Lecture Topic Task] Applying Communication Strategies to Improve Route Planning

### ISSUE THREAD

**Issue by yamayrie** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#168]
Add a new section on applying communication strategies to improve route planning to the documentation. It explores the strategies of the app and how our team optimized notifications so users can receive information and keep channels open for feedback and improvement.

**Comment by yamayrie** [comment]
added it to the documentation

**Comment by gabrielpadilla7** [comment]
closing as completed
