### ISSUE TITLE
[Lecture Topic Task] Applying Analysis Patterns

### ISSUE THREAD

**Issue by Alej24** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#171]
The objective is to create a model that applies the information in the "Applying Analysis Patterns" presentation.

**Comment by gabrielpadilla7** [comment]
Has this been documented in the changelog section? Also, please provide urgency and difficulty assignments so you can get points for this task

**Comment by Alej24** [comment]
Done
