### ISSUE TITLE
[Documentation] 1.2.1 current situation

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#19]
Write in doc: https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit?usp=sharing 
Stating 1.2.1 part of (Evaluation Criteria and Guidelines - Milestone 1).

------------------------------------------------------------------------------------------------------------------------
 Try to use this section to prepare for the next section of
    needs. For example in a project concerned with used car owner/repair
    history you could emphasize the point that there is a large used car
    market and that for used cars information about the car's history is
    more important than for new cars.
  • If you have to make reference to data like percentages or estimates,
    its good if you include where you found it or a source.

**Comment by MrL9000** [comment]
Proof: https://docs.google.com/document/d/1fe0ptxNmBY8BB-Ja9j2-G-sCbOxHrC67bJ4-54YousI/edit

**Comment by Yahid1** [comment]
Its on spanish

**Comment by Yahid1** [comment]
Tiene que ser en ingles.

**Comment by Yahid1** [comment]
It should also be put in this doc: https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit

**Comment by MrL9000** [comment]
I have implented these changes, https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit.

**Comment by gabrielpadilla7** [comment]
Is there a possiblity you could expand with more details on it? If not, it is ok, it provides a good foundation for the current situation in milestone 1 @MrL9000

**Comment by Yahid1** [comment]
Modifications look good.
