### ISSUE TITLE
[Documentation] Fix section 4.1 AND 4.4 based on Professor's Feedback

### ISSUE THREAD

**Issue by JConcepcion01** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#191]
Address notes made by the professor on the Documentation. Please refer to the following document for more details: https://docs.google.com/document/d/1iqslezp9a2G_6m-8B7yVRagj3M7xjivETaEn-bo2t2M/edit?usp=sharing

**Comment by juan-ortiz92** [comment]
Is the feedback given for 4.1 that we need to change it to an overview or that the section looks like an overview and must be changed?

**Comment by Yahid1** [comment]
What was written in this section is only an overview and does not seem implemented.

**Comment by Yahid1** [comment]
If you believe it was already implemented please point it out in the Doc.

**Comment by gabrielpadilla7** [comment]
closing as completed
