### ISSUE TITLE
[Lecture Topic Task] Refactor DriverListComponent to Separate Business Logic and UI Logic

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#201]
***Problem Description:***
The ```DriverListComponent``` currently combines both business logic and UI logic within the same class. This violates the principle of separation of concerns, making the code harder to maintain and test. The document "10Breakthrough.pdf" emphasizes the importance of simplifying the model and reorganizing code to gain deeper insights and achieve a more maintainable structure. Applying this principle involves refactoring components to create clearer boundaries between different types of logic.

***Areas Identified with Mixed Logic:***

  - ```editDriver``` Method:
  Contains business logic involving API calls (```driverApi.updateDriver```) and presentation logic with user notifications (```messageService.add```) and dialog handling (```this.editDriverDialog = false```).

  - ```saveDriver``` Method:
  Integrates API interactions to create a driver and reloads driver data, mixed with UI logic such as showing confirmation dialogs and displaying success/error messages.

  - ```deleteDriver``` Method:
  Includes the logic to confirm deletion and interact with the API (```driverApi.deleteDriver```) alongside UI notifications.

***Proposed Solution:***
  Refactor the ```DriverListComponent``` to focus solely on UI interactions and delegate business logic (API calls, data handling) to a dedicated service class, ```DriverFacade```. This will improve code modularity, enhance readability, and align with the principle of refactoring to simplify and separate responsibilities, as suggested by the concepts in "10Breakthrough.pdf".

***References:***
  - Document: [10Breakthrough.pdf](https://github.com/user-attachments/files/17694898/10Breakthrough.pdf) (Principles of refactoring for better structure and insights)

Code Files:
  - [driver-list.component.ts.txt](https://github.com/user-attachments/files/17694911/driver-list.component.ts.txt): Contains methods that mix business and UI logic.
  - [driver-api.service.ts.txt](https://github.com/user-attachments/files/17694919/driver-api.service.ts.txt): API service currently used directly in the component.

**Comment by Yahid1** [comment]
Is this documented in the Milestone #3 documentation??

**Comment by Yahid1** [comment]
Good Job
