### ISSUE TITLE
Identify Specification Patterns (Metrics Team)

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#204]
Identify any instances where the Specification pattern was used in the Vehicle tab, and any areas where code could be updated or refined to follow the specification pattern.

**Comment by MrL9000** [comment]
In spite of this task not yet being reviewed by the Managers, the task has been done, please contact me once this task has been confirmed to be good to go so that I implement the document in the Milestone #/3 documentation.

here's my work: https://docs.google.com/document/d/1HGw3LLu9egepT_cp9byU_gJ35K1W-3GvY8JsfGacJ6Q/edit?usp=sharing

**Comment by Yahid1** [comment]
Good work. This should get added to the Doc.

**Comment by Yahid1** [comment]
When thats done I will close this task.

**Comment by MrL9000** [comment]
Added to the doc, 5.13 Vehicle Menu Flowchart. https://docs.google.com/document/d/1cckJSSO8kLDqyC-MK7YW6j686_s-D5HrGuQ3lRCx4xE/edit?tab=t.0

**Comment by gabrielpadilla7** [comment]
@MrL9000 In the beginning there's a part that says [Model goes here(am unable to implement the drawing)]. What's up with that? Should that be there or was it left there accidentally?

**Comment by MrL9000** [comment]
ooh yea I forgot about that, for some reason I can't implement drawings

**Comment by MrL9000** [comment]
oh wait, now I can implement it, hold on

**Comment by MrL9000** [comment]
@gabrielpadilla7 fixed it, check

**Comment by gabrielpadilla7** [comment]
closing as completed
