### ISSUE TITLE
[Lecture Topic Task] Applying Domain-Driven Design to the Trolley Tracker App

### ISSUE THREAD

**Issue by yamayrie** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#205]
See how domain-driven design concepts were applied to improve the Trolley Tracker app. It focuses on aggregates, iterative testing, and domain knowledge integration

**Comment by yamayrie** [comment]
Concepts like aggregates, user centered design, and iterative development were used to improve the Trolley Tracker app. It focuses on how developers combined domain knowledge, defined aggregate boundaries, and tested the app by imitating user roles to make sure that that the system is understandable.

**Key Components:**
1. **Integration of Domain Knowledge:**

- We modeled important ideas like buses, routes, and bus stops using domain-driven design concepts.
- Observations of real-world trolley operations (e.g., signaling trolleys, understanding route patterns) shaped the app’s functionality.
- We collected feedback during simulation-based testing informed adjustments to make sure the system aligned with user needs.

2. **Aggregates in the System Design:**

- The domain was organized using aggregate concepts. For example, the Trolley was identified as the root entity, and included related metrics like sensor data, routes, and notifications.
- Developers decided what should be contained in the aggregate to make sure it has clarity and maintainability

3. **Iterative Design and Developer Testing:**

- Developers controlled testing by replicating the experiences of students, faculty, and administrators.
- The team tested and adjusted the app’s features, like real-time tracking and notification settings, to meet domain-specific challenges based on class discussions about iterative feedback.

We used class topics to establish a ubiquitous language for clear communication among the team. In code and documentation, words like "route," "delay," and "real-time tracking" were defined and used. The team practiced digital anthropology by closely observing and documenting trolley operations to reduce domain ignorance.

The app was iteratively refined based on developer testing. It improved real-time updates, route visibility, and notification clarity. Aggregate boundaries made sure that the app remained modular and manageable with different responsibilities for each domain entity. Constant use of a common language reduced ambiguity and improved communication during development.

**Comment by yamayrie** [comment]
added to documentation

**Comment by gabrielpadilla7** [comment]
closing as completed
