### ISSUE TITLE
[Lecture Topic Task] Provide aditional examples of Intention-Revealing Interfaces

### ISSUE THREAD

**Issue by AlexisTraversoPR** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#215]
Document additional examples of intent-revealing interfaces and discuss original examples of these interfaces that were in the code handed to us and the importance of keeping this intent and reinforcing it moving forward with new functions.

**Comment by gabrielpadilla7** [comment]
closing as completed
