### ISSUE TITLE
[Lecture Topic Task] Define the Ubiquitous Language for the RUMBus Dashboard

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#216]
In software design, particularly in the context of Domain-Driven Design (DDD), establishing a **ubiquitous language** is critical to ensure clear communication and alignment between developers, stakeholders, and users. According to the concepts outlined in the provided PDF [08UsingTheLanguage.pdf](https://github.com/user-attachments/files/17935686/08UsingTheLanguage.1.pdf), a shared language helps avoid ambiguity and ensures that terms used in
 the application accurately reflect the domain model and its requirements.

This task involves defining a ubiquitous language for the RUMBus Dashboard. It includes identifying and documenting key terms, entities, and actions used in the system. These terms will serve as the foundation for consistent communication and implementation across the development team and stakeholders.

By completing this task, the team will:

1. Establish a shared understanding of critical domain concepts.

2. Align the terminology used in the UI, codebase, and documentation.

3. Reduce misunderstandings and improve development efficiency.

The outcome of this task will directly influence the design and implementation phases of the dashboard.

**Comment by Janiel777** [comment]
Seccion 5.16 de la documentacion. Todo esta en texto verde.
![image](https://github.com/user-attachments/assets/da87ad8b-5449-433f-8eab-f74e86577f9a)

Se añadio al chanelog tambien.
![image](https://github.com/user-attachments/assets/01349138-5bd2-4a9d-9bb4-3fb2f2a7e5d8)

**Comment by Janiel777** [comment]
@Yahid1 @gabrielpadilla7 Listo para revision.

**Comment by Yahid1** [comment]
Good
