### ISSUE TITLE
[Lecture Topic Task] Create a UML Diagram for TypeScript Models in src/app/models

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#218]
**Description**
This task involves creating a UML diagram to visually represent the relationships and structure of the TypeScript models defined in the src/app/models directory of the project. The diagram will help developers and stakeholders better understand the project's domain and its key entities.

**Context**
The task aligns with concepts discussed in the provided PDF documentation, specifically related to Domain Modeling and Communication and Language:

**Effective Domain Modeling (PDF):**
Ensures the domain structure is well-communicated and understood by the development team.
Highlights dependencies, relationships, and responsibilities within the system.

**Communication and the Use of Language (PDF):**
Establishes a Ubiquitous Language by standardizing entity relationships and their meanings in the domain.

**Comment by Janiel777** [comment]
Se añadio a la documentacion en texto verde.
![image](https://github.com/user-attachments/assets/6dfc3d45-5a16-42b7-aa76-a3a9286c4258)

Se creo el diagrama y se anadio a la documentacion con un link
![image](https://github.com/user-attachments/assets/c690eac5-f1c9-42b0-b752-5d25d46bfbfc)

Se añadio al chanelog
![image](https://github.com/user-attachments/assets/df760b32-baff-4496-8815-08d70d671a57)

**Comment by Janiel777** [comment]
@Yahid1 @gabrielpadilla7 Listo para revision.

**Comment by Yahid1** [comment]
Good Job
