### ISSUE TITLE
[Documentation] 1.2.3 ideas

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#22]
• You can include some features of the system-to-be, but refrain from
    going too much into the requirements of the system-to-be.
  • Do not go too much into specifics here (e.g. implementation)
    details. Show the idea in a concise manner. Bring out the idea
    clearly.

**Comment by Janiel777** [comment]
1.2.3 Ideas
The development of the application will focus on improving the student experience when using the campus transportation system through the following features:

Real-time monitoring: The application will allow users to track the exact location of trolleys in real time, facilitating informed decision making about when and where to board vehicles, thereby reducing wait time and uncertainty. This will not only improve the student experience, but will also contribute to more efficient use of the transportation system.

Friendly interface: An intuitive and easy-to-use interface will be designed, allowing students to quickly consult necessary information, such as estimated arrival times, available routes, and possible changes in transportation service. The simplicity of the interface will seek to reduce interaction time, maximizing accessibility for users of different technological levels.

GPS and interactive maps integration: The application will use GPS technology to display the current location of trolleys on an interactive map. Students will be able to view routes in real time and plan their transportation more accurately, optimizing their time and reducing unnecessary waiting times at stops.

Route planning: A route planning system will be included that will allow users to view the best transportation options based on their location and destination, taking into account real-time demand and traffic. This will allow users to customize their routes, optimizing their mobility on campus.

Notifications and alerts: The application will send notifications in case of delays, route changes, or service interruptions. In addition, it will allow users to configure personalized alerts based on their preferred routes, providing an experience more tailored to individual needs.

Scalability: The application will be designed to adapt to the growth of the transportation service, with the possibility of adding new routes, more trolleys, and additional functionalities without compromising system performance. In addition, its scalability will be considered to implement it in other universities and private transportation companies, allowing its expansion to different contexts using the same system and thus promote greater adoption of the platform.

Admin Dashboard: A separate application will be implemented exclusively for the administrators of the transport system. This platform will allow administrators to view all information related to the trolleys in an organized manner, including details such as location, maintenance status, fuel and other relevant parameters. In addition, administrators will receive real-time reports on the status of the vehicles, allowing them to make quick and effective decisions to ensure optimal operation of the transport system.

**Comment by gabrielpadilla7** [comment]
closing as completed
