### ISSUE TITLE
[Lecture Topic Task] Designing Aggregate Roots for Transportation Systems with Consistency Constraints

### ISSUE THREAD

**Issue by AleDiazz** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#223]
Add a sub-lecture topic under Section 4.17 Maintaining Model Integrity to describe how aggregate roots like "Trolley," "Driver," and "Route" were used to maintain system consistency and enforce constraints. Include examples of constraints, such as preventing overlapping driver assignments, and explain how refactoring aggregates supported real-time updates and reduced conflicts.

**Comment by Yahid1** [comment]
Its something.
