### ISSUE TITLE
[Documentation] 1.3.1 scope and span

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#23]
• Scope should broadly go over all aspects of your project, such as
    domain, requirements, implementation, etc. Scope is also about the
    broad area in which your project is operating. For example, (to be
    further detailed) tourism, water-sports, beach activities, community
    forum, social recommendation system, group scheduling,
    entertainment, gaming, event planning, … But elaborate it some
    more. Span is the more specific concern of the project. For example,
    groups of typically 3-6 players/master (and rarely up to 10), …
  • For example, scope describes university student spacial and temporal
    orientation and support, span describes this more specifically (UPRM
    students, GPS, classrooms, assignments, …).
  • Span is related to scope: in scope you discuss the more general,
    more high-level view. In span you go more after the specifics. For
    example, you could have a section in the descriptive part on
    "methodology" and describe the agile methodology and how you are
    using it there.
  • Is your scope realistic? For example in a project concerned with
    offering families a go-to place to find casual games: Can you
    actually develop several such games or are you only curating them?
  • In general implementation decisions do not belong in the scope and
    span. You could mention them in the design brief or you could not
    mention them at all in the informative part, but characterize the
    relevant goals that you have and then explain in the descriptive
    part (and maybe to some extent in the analytic part) your reasoning
    for choosing the implementation technology.
  • Scope and span should focus on the project not so much on the
    result. For example, having a stable internet connection does not
    seem to belong here.
  • Scope includes all those things you will do on the project. Include
    domain engineering, requirements engineering, software architecture,
    …

**Comment by Janiel777** [comment]
# University Transportation System Project

The project aims to develop an integrated transportation system, composed of a mobile application for students and an **Admin Dashboard** for administrators. This system is focused on improving the transportation experience within university campuses. Through the application, students will be able to track the location of trolleys in real time, plan their routes and receive notifications about service changes. Administrators, for their part, will be able to manage and monitor the operation of the vehicles, optimizing their use. The project encompasses a series of technical and management activities, such as requirements gathering, software architecture implementation, testing and deployment.

## Scope

- **Domain:** The system will cover internal transportation of university campuses, with the possibility of expanding to other campuses and private transportation companies in the future. It will focus on improving the mobility of both students and university staff, using real-time tracking technology using GPS and interactive maps. This will allow for greater efficiency in the daily operation of transportation.

- **Requirements:** Key requirements include real-time tracking capability, route planning, customized notifications for students, and an **Admin Dashboard** that will allow administrators to monitor vehicle status and receive real-time reports. It will also be ensured that the system is scalable for future expansion without affecting its performance.

- **Implementation:** The system will be developed as a mobile application for Android and iOS platforms, complemented by an **Admin Dashboard** accessible through a web browser. The platform will use GPS tracking technologies and real-time notifications, with a friendly graphical interface for end users and administrators. The implementation will be done in phases to ensure a gradual and efficient rollout.

- **Activities:** Key project activities include collecting user data to define specific requirements, implementing the system in phases, usability testing, maintenance and optimization based on user feedback. This will allow for continuous system improvement and a more effective user experience.

- **Users:** The primary users will be the students and university staff who use the transportation system, while system administrators will be responsible for managing the daily operation of the vehicles. The participation of both groups is crucial to the success of the project.

## Extension (Span)

- **Specificity:** The system is specifically designed to manage transportation within university campuses, initially covering all trolley routes. However, the possibility of expanding its use to other areas of the campus or integrating the system with private transportation companies that can benefit from it is also contemplated.

- **Geographic coverage:** The system will initially be implemented on the Mayagüez campus, covering all routes operated by trolleys, with the possibility of expanding to additional routes or peripheral areas that connect to the campus. In the future, implementation on other university campuses may be considered.

- **Scalability:** The system will be scalable, allowing for the addition of new functionalities, routes, and vehicles as the transportation system grows. The **Admin Dashboard** will also adapt to different management scenarios, whether for additional campuses or private transport companies, ensuring its flexibility and efficiency in the long term.

**Comment by gabrielpadilla7** [comment]
Very good job! Closing as completed
