### ISSUE TITLE
[Documentation] 2.1.1 domain rough sketch

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#24]
docs: https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit?usp=sharing

2.1.1 domain rough sketch

  • Rough sketches are meant for collecting unprocessed information (or
    ideas) for example from brainstorming sessions, interviews,
    literature review,record meetings, Q&A… Your domain description
    rough sketch looks a bit too processed. What you write might better
    be placed in the domain narrative since it tells the story of the
    domain.

  • The 'rough domain sketch' would include the specifics that you were
    told.

  • The rough sketch focuses almost completely on the features that will
    be included in the application that will be developed as well as
    descriptions of how they should work. The domain is independent of
    any system-to-be and consists of the concepts and phenomena "out
    there" in the observable universe that are of interest to your
    project. Your rough sketch is not an unfiltered snapshot of the
    initial discussions of the domain that led to the formulation of the
    current situation. I suggest that this part be completely redone.

  • Your rough sketch is not rough it's quite polished and could just as
    well be the narrative. Rough sketches are meant for collecting ideas
    in brainstorming, record meetings, Q&A, clippings from the
    literature, … Then you analyze the rough sketch (documented in
    concept analysis) and you write the domain narrative using the new
    concepts and the details from the rough sketch.

  • What you have in the rough sketch of the domain is already quite
    processed.

  • Rough sketches are unprocessed, often containing a lot of
    specifics. The concept analysis goes over the rough sketch and
    abstracts out meaningful concepts that help structure the specifics
    in the rough sketch. Based on this you then write the narrative.

**Comment by gabrielpadilla7** [comment]
Closing as completed
