### ISSUE TITLE
Main Design Template

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#25]
Using Figma, you will create a small template for how the application will look like. This template will then be used to design more detailed app designs.

**Comment by Yahid1** [comment]
Can you point me towards evidence of the task done?

**Comment by MrL9000** [comment]
ah, yes, I forgot, here you go. https://www.figma.com/design/NUGiYJUwDDOcIYlnhtZjy9/Untitled?node-id=0-1&t=ic3b8OJ6MaiLgohZ-1

**Comment by Yahid1** [comment]
Perfect
