### ISSUE TITLE
Menu Design

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#26]
Using the template from issue #25 , you will design in Figma a main menu design for the application. This must follow the template, as it will be the design we will be using for the rest of the semester. 

Keep in mind the Trolley Metrics & Maintenance section and its objectives.

**Comment by warm007** [comment]
<img width="876" alt="MENU DESING" src="https://github.com/user-attachments/assets/7f17b04a-4695-428d-8859-167d3f9b0bdd">

**Comment by warm007** [comment]
Greetings! Here I upload an image of the menu redesign. If you need anything else, feel free to let me know.
