### ISSUE TITLE
[Documentation] 1.5 derived goals

### ISSUE THREAD

**Issue by JoelTorres20** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#30]
Write in doc:
https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit?usp=sharing

1.5 derived goals

Your primary goal is described by earlier sections like the current
  situation, the needs you identify, etc. Aside from your primary goal
  your project likely has some secondary goals.

  • Your primary project goal is described by the other sections:
    current situation, needs, ideas, … Here you talk about secondary
    desirable outcomes. These should be substantially different from
    your primary goals and not just reiterations of those primary
    goals. For example, a project concerned with beach quality
    monitoring might have as its primary goal to give information about
    the cleanliness of the water and the beach to beach-goers. A
    secondary goal could be to increase tourism to some lesser known
    beaches or to raise awareness among the public about the need to
    keep the beaches clean.

**Comment by gabrielpadilla7** [comment]
Marked as completed, closing
