### ISSUE TITLE
[Lecture Topic Task] Identifying the first order ignorance relevant to the establishment of the codebase which are Specific to Team 1

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#32]
The Identification of First order problems relevant to the establishment of the codebase, which are further oriented to the interests of Team 1

**Comment by MrL9000** [comment]
tweaked the language a bit, the name is first order ignorance, not first order problems

**Comment by MrL9000** [comment]
https://docs.google.com/document/d/17WdHrsFhjTuesdw9d1o4iP41-yC58K0vgVQvBCwBTpI/edit?pli=1

**Comment by gabrielpadilla7** [comment]
Has this been added to the documentation? For reference, here is the documentation link that we're using at the moment: https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit

**Comment by Yahid1** [comment]
Good work
