### ISSUE TITLE
[Documentation] 2.2.1 user stories, epics, features

### ISSUE THREAD

**Issue by yamayrie** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#33]
- Epics are like user stories, but larger. So, an epic cannot be implemented in a single sprint and needs to be broken into smaller user stories that together make up the epic. Epics can use the same "at a XYZ I want to ABC in order to HIJ." format. Remember it's important to connect the user story, epic, or feature to a more abstract goal that the kind of stakeholder would have.
- Find the right granularity for the user stories. On the one hand you do not want them to be too broad. As in "as a student I want to get my enrollment done in order to have time to do more interesting things". In this case try zooming in and breaking them apart into smaller user stories. On the other hand you don't want them to be too detailed. As in "as a student I want to click a square button in order to submit my entries in the current screen". In this case take a step back and see what the higher-up task is to which this contributes. Look for meaning to the student's enrollment tasks themselves: does this mean anything in the context of the student enrolling?

**Comment by yamayrie** [comment]
Added documentation information regarding user stories, epics, and features:

2.2.1 User Stories, Epics, Features

**User Stories**

1. As a student, I want to view the real-time location of trolleys on campus so that I can minimize my wait time and plan my trips efficiently.
2. As a faculty member, I want to receive notifications about route changes or delays so that I can adjust my schedule accordingly.
3. As an administrative staff member, I want to monitor trolley performance metrics to ensure the system is running smoothly and address maintenance needs promptly.

**Epics**

**1. Real-Time Trolley Tracking and Schedule Updates**
- **Description:** This epic focuses on providing users with real-time tracking and scheduling information for the trolley system. It includes features such as live trolley location on a map, estimated arrival times at stops, and notifications about schedule changes.
- **Success Metric:** The success of this epic will be measured by the accuracy and reliability of the real-time tracking data, as well as user satisfaction with the ease of accessing schedule updates. Metrics like reduced wait times and positive user feedback will be used to gauge success.

**2. Route Planning and Notifications**
- **Description:** This epic aims to enhance the user experience by offering route planning tools and timely notifications. It includes features such as suggested routes based on user input, alerts about route changes or delays, and real-time updates about route availability.
- **Success Metric:** The success of this epic will be measured by user engagement with the route planning features and the effectiveness of the notification system in keeping users informed. Metrics like user adherence to suggested routes and the percentage of users utilizing notifications for planning will be assessed.

**3. Trolley Metrics & Maintenance Dashboard**
- **Description:** This epic involves developing a dashboard for administrative staff to monitor trolley performance and maintenance needs. It includes features like displaying real-time data from trolley sensors, visualizing metrics through graphs, and issuing maintenance alerts based on sensor data.
- **Success Metric:** The success of this epic will be measured by the accuracy and usefulness of the data presented on the dashboard. Metrics such as the frequency of maintenance issues detected and addressed promptly, as well as staff feedback on dashboard usability, will be considered.

**4. Notification System for Trolley Maintenance**
- **Description:** This epic focuses on implementing a notification system that alerts both administrative staff and users about maintenance-related issues. It includes sending internal alerts for maintenance needs and external notifications to users about trolley service disruptions.
- **Success Metric:** The success of this epic will be measured by the responsiveness to maintenance alerts and the effectiveness of communication to users about service disruptions. Metrics like reduced downtime due to maintenance and positive user feedback on the clarity of notifications will be evaluated.

**Features**

1. **Live Trolley Map:** Displays the current location of trolleys on a campus map, providing real-time tracking and estimated arrival times at stops.
2. **Route Planning Tool:** Suggests optimal routes and schedules based on user input, adapting to changes in demand and traffic patterns.
3. **Maintenance Dashboard:** Provides a visual interface for monitoring trolley performance metrics, including speed, location, and fuel levels, along with maintenance alerts.
4. **Push Notification System:** Sends notifications to users about route changes, delays, and maintenance disruptions, ensuring they stay informed and can plan accordingly.

**Comment by Yahid1** [comment]
Good Job
