### ISSUE TITLE
[Documentation] 2.2.2 personas

### ISSUE THREAD

**Issue by yamayrie** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#34]
- Include personas in your documentation. They allow you to justify user stories, features, epics, and requirements in general. A good way to start developing your personas is to think about yourself (if you are a potential user), friends, family, peers, etc. Anyone you might want to make use of your software and benefit from your project. Then you identify what all these people have in common and you condense their important traits into a few "Frankensteins", imaginary people whom you give certain traits that you think are plausible for a single person to have. Your main goal here: you collection of traits must be easy to remember for everyone around the team so that just mentioning the name of the persona immediately evokes the traits in everyone's mind.

**Comment by yamayrie** [comment]
Added documentation information regarding personas:

2.2.2 Personas

**Persona #1**
- **Name:** Diego Ramirez
- **Occupation:** Full-Time Student, Campus Tour Guide
- **Interests:** Passionate about urban planning, enjoys helping new students, and loves hiking
- **Age:** 22
- **About:** Diego was born and raised in Ann Arbor, Michigan, on February 15, 2002. Since childhood, he's been fascinated by how cities are designed and how people move through them. He chose to study Urban Planning at his university to understand the complexity of transportation systems and their impact on daily life. As a campus tour guide, he regularly helps new students find their way around the large university grounds and has knowledge on the drawbacks of the existing trolley system. He is known as one of the best student when it comes to handling the campus with effectiveness. Diego enjoys organizing and arranging things, but when he has to wait for unreliable trolley schedules it frustrates him. This usually results in him being late for class. He hopes to contribute to making the campus transportation system reliable for all users.

**Persona #2**
- **Name:** Dr. Janine Brooks
- **Occupation:** Professor of Environmental Science
- **Interests:** Environmental conservation, gardening, and yoga
- **Age:** 45
- **About:** Dr. Brooks is passionate about environmental sustainability and has been a university instructor for more than 15 years. She was born on August 22, 1979, in Hershey, Pennsylvania, and has always had a strong interest in the environment and how people impact it. During her lectures, she encourages students to think critically about ecological issues. The trolley system is a vital part of Dr. Brooks' daily routine because she routinely travels across campus to teach different classes and attend meetings. She believes that systems that promote sustainability and efficiency are crucial, but inaccurate information about the timings frequently throws off her day, adding needless worry. She believes a more efficient trolley system with real-time updates could not only benefit her but also align with the university's commitment to reducing its carbon footprint.

**Persona #3**
- **Name:** Oliver Reed
- **Occupation:** Full-Time Student, Part-Time App Developer
- **Interests:** Coding, esports, and exploring new tech gadgets
- **Age:** 22
- **About:** Oliver was born in San Francisco, California, on December 10, 2001. His early interest in computers led him to pursue a degree in computer science. Oliver works on side projects and develops applications. He enjoys experimenting with new methods to increase the effectiveness of daily tasks. Even though he is independent, he finds the campus trolley system annoying because it doesn't have real-time tracking. His schedule gets thrown off when he tries to guess when the next trolley will arrive. Oliver thinks it would be rewarding to contribute to the design of the trolley tracker application. For him, a good system would link with other apps he uses on a regular basis in addition to providing precise arrival times.

**Persona #4**
- **Name:** Carolina Méndez
- **Occupation:** Administrative Staff, Transportation Coordinator
- **Interests:** Data analytics, improving campus services, and baking
- **Age:** 33
- **About:** Carolina was born on June 5, 1991, in Chicago, Illinois. For the last five years, she has served the university in the position of Transportation Coordinator. Her duties encompass managing the trolley system, making sure it works well, and searching for opportunities to make it more efficient. Like many data-oriented managers, Carolina wants to enforce the use of order-related data analysis plus feedback from the end-user to consider better transport solutions. Her position allows her to handle various complaints and suggestions coming from students and faculty, which is important because it shows her the areas in which the system fails. As focused as she is on task, it is a problem to deal with a situation where there are no timely measures to be taken because there is no simple application to observe and control trolley metrics. Carolina is not only looking forward to the improvement in user interaction brought by the new app but also to be able to use the app to analyze data for effective routing and scheduling.

**Persona #5**
- **Name:** Sofia Díaz
- **Occupation:** Part-Time Student, Working Mom
- **Interests:** Balancing work, studies, and family, enjoys yoga and cooking
- **Age:** 28
- **About:** Sofia was born on January 18, 1996, in El Paso, Texas. She is currently a part-time student pursuing a degree in Business Administration while juggling a job and taking care of her two kids. Her days are planned to make sure she can attend classes, complete assignments, and spend enough time with her family. Sofia relies a lot on the campus trolley system to get to her classes on time without being stressed about parking, except that the unpredictability of the trolley schedules often causes delays in her days. She is looking forward to the trolley tracker app, which she hopes will allow her to better plan her day and reduce the time she spends waiting for transportation.

**Comment by gabrielpadilla7** [comment]
Completed. Closing now
