### ISSUE TITLE
Milestone Presentation

### ISSUE THREAD

**Issue by JConcepcion01** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#35]
Create a presentation with all the milestone objectives showing the information that will be useful for the video. This includes creating the design and template as well as relevant information that will presented. It concerns both the Metrics Team and Notification Team.

**Comment by gabrielpadilla7** [comment]
This is a duplicate issue, the other issue was created first but was in drafts. Please modify the issue or it will be closed as not planned. @JConcepcion01
