### ISSUE TITLE
[Documentation] 2.1.3 domain terminology in relation to domain rough sketch

### ISSUE THREAD

**Issue by SebastianSaliva** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#37]
[document](https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit?usp=sharing)

This task consists in making the "domain terminology in relation to domain rough sketch" section of the documentation

_Ideally more than one person should work on this task._

  • The domain terminology is not part of the rough sketch: to develop
    the terminology you have to analyze the rough sketch and come up
    with good definitions for the terms used e.g. in stakeholder
    interviews. So, the definitions are results of the processing and
    are therefore not rough.

**Comment by Yahid1** [comment]
Good enough
