### ISSUE TITLE
[Documentation] 2.1.5 Events, actions, and behaviors

### ISSUE THREAD

**Issue by dylanDeJesus21** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#38]
There is a difference between the moment from which a person has just become a member (event), the act of becoming a member (action), and the process consisting of various smaller actions that together make up the "becoming a member" (behavior).

**Comment by gabrielpadilla7** [comment]
@dylanDeJesus21 This is a duplicate issue, please modify or it will be closed as not planned

**Comment by gabrielpadilla7** [comment]
@dylanDeJesus21 work can be done for this issue, plans have been changed. Please continue working on it, sorry for the confusion.

**Comment by Yahid1** [comment]
Good
