### ISSUE TITLE
Create a playlist of important videos explaining Angular

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#41]
Create a Github Discussion with videos helpful to understand the Angular 18 framework.

**Comment by dylanDeJesus21** [comment]
[Angular_Tutorial.pdf](https://github.com/user-attachments/files/17069650/Angular_Tutorial.pdf)
In this link, there is a list of 5 Angular related videos and tutorials so you can get to know the basics and the fundamentals.

**Comment by Yahid1** [comment]
Do not close the task
