### ISSUE TITLE
[Documentation] 2.1.5 events, actions, and behaviors

### ISSUE THREAD

**Issue by dAninAd1248** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#43]

**Comment by gabrielpadilla7** [comment]
#38 @dAninAd1248 this issue is a duplicate. Either change the section that you will work on the documentation or this issue will be closed as not planned.

**Comment by gabrielpadilla7** [comment]
I heard this issue was made first, so I will allow this issue to be completed, sorry for the confusion.

**Comment by gabrielpadilla7** [comment]
Issue will be closed as not planned, as the other instance of this issue will be completed
