### ISSUE TITLE
[Lecture Topic Task] Design as Problem Solving

### ISSUE THREAD

**Issue by dylanDeJesus21** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#48]
Designing as problem solving means approaching a challenge by identifying specific needs or issues and developing creative, practical solutions to address them. It involves understanding the problem in detail, setting clear requirements, and making thoughtful design choices to meet those requirements. This process often considers factors such as size, speed, user experience, and adaptability to ensure the final solution is both functional and fit for its intended purpose. Ultimately, design as problem solving aims to create effective, efficient systems or products that solve real-world problems.

Changes are on 4.6 section
https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit?usp=sharing

**Comment by Yahid1** [comment]
Its good
