### ISSUE TITLE
[Lecture Topic Task] Trolleys: Studying our Domain

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#50]
Explaining of our domain and what should developers know about the trolley system before attempting to code a solution. This document should include: trolley routes, trolley administration, students, trolley drivers, hours of service, etc. The purpose of this task is to clearly lay out the current situation of the developers knowledge of the trolley system and what questions should developers try to answer while investigating the domain.

**Comment by Yahid1** [comment]
Perfect
