### ISSUE TITLE
Implement a visible button to pull down the notifications menu

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#54]
Description:
Looking through the code, I noticed that there were already some mockup notifications being added to an array in the notification.service.ts file, and that there was also a notifications menu defined in the application. However, when running the application, I was unable to display this menu. Upon further investigation, I discovered that this right side menu did not have a button to display it, which prevented it from being accessible. I continued investigating and realized that there is already a function to display this menu, but using tools to search for specific text in all the files in the project, I realized that the toogleNotificationsSideMenu() function defined in navbar.service.ts was not being used anywhere.

Objective:
The objective of this issue is to implement a visible and friendly button, with a bell icon or similar, in the toolbar to allow the user to display the right side menu of notifications.

**Comment by Yahid1** [comment]
Can you show a picture of the completed task.

**Comment by Yahid1** [comment]
![Image](https://github.com/user-attachments/assets/638a9079-4efb-45db-a91e-f70518da7d1f)

I can see it. Looks good.
