### ISSUE TITLE
Improved the design of the notifications sidebar to optimize layout and visual style

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#55]
Description:

While digging through the code, I noticed that there is a notifications sidebar that is not visible because a button to display it has not been implemented yet. To force this menu to be displayed and to be able to work on its design, the values ​​of the variables rightSideMenuOpen and rightSideMenuOpenNotifications can be changed to true in the navbar.service.ts file, which allows the notifications sidebar to be visible without having to create a button to display it. This is just so we can work on the progress of this issue, but these values ​​will remain false when the issue is finished.

This issue will focus solely on the design of the container and the menu that displays the notifications, not on the design of the individual notifications.

Tasks:

- Review and improve the design of the notifications sidebar.

- Optimize the spacing, fonts, colors, and layout of the menu container for a better visual experience.

- There will be no work done on the design of individual notifications in this issue, only on the container that contains them.

**Comment by Yahid1** [comment]
Can you provide a picture or a link to the branch of what you did?

**Comment by SebastianSaliva** [comment]
Settings icon and header now appear in the same line and added a horizontal line for more clarity
[branch link](https://github.com/uprm-inso4116-2024-2025-s1/RUMBus-Dashboard.git)

<img width="540" alt="image" src="https://github.com/user-attachments/assets/a240ccff-4148-431a-bcee-7662eecfb5e1">

**Comment by Yahid1** [comment]
Am unfortunately this does not complete the task at hand. Its missing refactoring the container that separates each of the notification containers.

**Comment by Yahid1** [comment]
Part of the container is done. Because of this I will give re evaluate the points given.

**Comment by SebastianSaliva** [comment]
> Unfortunately this does not complete the task at hand. Its missing refactoring the container that separates each of the notification containers.

I don't think you can really refactor the container that holds the notifications, that container is a 1 column table which is automatically filled with templates of notifications. The spacing between each notification is defined automatically by the table. I think this is why improving the notifications themselves are a different issue. Nevertheless I do not mind if the points for the task are re-evaluated

**Comment by Yahid1** [comment]
No problem, I merged your code to main and since it wasn't that much code I lowered the points.
