### ISSUE TITLE
External Notification Research Possibility/Viability

### ISSUE THREAD

**Issue by JoelTorres20** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#58]
Do research and find out if external notifications (web app phone notifications) are possible and viable via angular.js and how hard it would be to implement it.

**Comment by JoelTorres20** [comment]
It is feasible to convert our existing Angular.js web project into a Progressive Web App (PWA), giving it native app-like capability on mobile devices. Angular has built-in support for PWAs via the @angular/pwa package, which includes necessary components such as a service worker and a manifest.json file to allow offline capabilities, caching, and push notifications. PWAs also require HTTPS to support capabilities such as service workers. While converting an Angular project to a PWA is very simple with Angular's CLI, the process mostly entails setting the service worker, ensuring safe deployment, and testing the app on multiple devices.

Converting our Angular.js project to a Progressive Web App (PWA) enables external notifications using push notifications. Integrating service workers into a PWA allows the app to receive push notifications even when the user is not actively using it. These alerts can be triggered externally using services such as Firebase Cloud Messaging (FCM) or other push notification systems. This allows for real-time updates or alerts to be sent straight to users' mobile devices or PCs, much like native app notifications.

**Comment by Yahid1** [comment]
Can you write this in Github Discussions?

**Comment by Yahid1** [comment]
I will close the task when that gets done.

**Comment by Yahid1** [comment]
Thank you
