### ISSUE TITLE
2.1.4 Narrative

### ISSUE THREAD

**Issue by Brandell13** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#61]
describes the current state and functionality of trolleys at the University of Mayaguez (UPRM)

**Comment by gabrielpadilla7** [comment]
#35 This is a duplicate issue. Either edit to do another section of the documentation or this task will be closed as not planned. @Brandell13

**Comment by gabrielpadilla7** [comment]
I heard this issue was created first because it was a draft for a while, I am sorry for the confusion, work can still be carried out in this issue.

**Comment by Brandell13** [comment]
to review in the documentation

**Comment by gabrielpadilla7** [comment]
Reviewed, closing as completed
