### ISSUE TITLE
[Lecture Topic Task] Clean Architecture and SOLID Principles

### ISSUE THREAD

**Issue by Brandell13** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#63]
Understand and apply the principles of Clean Architecture

**Comment by gabrielpadilla7** [comment]
Has this been added to the documentation? For context, here is the link for the documentation: https://docs.google.com/document/d/1qkUBVgzOydIKMYa00yfAjvfVfEd_iJnqUeug9Wo4OLo/edit

**Comment by Brandell13** [comment]
I already added it to the documentation in the LTT section

**Comment by gabrielpadilla7** [comment]
Closing as completed
