### ISSUE TITLE
Menu Interactive Button Design 

### ISSUE THREAD

**Issue by warm007** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#70]
Description:

Design pressable buttons for the menu to improve user interaction. The buttons should include functionality such as an ownership filter view. Follow the existing design guidelines from issues #25 and #26. 

(Suggestions: Use Figma or a similar tool for mockups and prototypes.)

**Comment by warm007** [comment]
<img width="442" alt="MENU DESING with Buttons" src="https://github.com/user-attachments/assets/f896df2f-dbf4-4831-a7a5-dfb4de026f16">

**Comment by warm007** [comment]
<img width="441" alt="FULL DATA TABLE" src="https://github.com/user-attachments/assets/8059bf37-528a-449d-bd82-04049d4a5e04">

**Comment by warm007** [comment]
<img width="730" alt="OWNERSHIP VIEW" src="https://github.com/user-attachments/assets/26a487b8-4f91-4f1b-a8f5-a8e320a9b9da">

**Comment by warm007** [comment]
<img width="729" alt="SELECTED OWNERSHIP VIEW" src="https://github.com/user-attachments/assets/e5b65839-c242-46ee-8523-f534f3b28d34">

**Comment by Yahid1** [comment]
Looks very good!
