### ISSUE TITLE
[Lecture Topic Task] Refactoring Vehicle Information 

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#75]
Refactor the previous section to look like this:
![Image](https://github.com/user-attachments/assets/2972cfeb-dbc4-4fe2-8c3e-9b7180e87191)

**Comment by warm007** [comment]
![image](https://github.com/user-attachments/assets/a4d543ea-03f7-4246-b06b-07f03aefd634)
