### ISSUE TITLE
Fix the order of the notifications

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#76]
The notifications are currently ordered from oldest to newest. Implement code that inverts that order and makes it so that the most recent Notification goes on the Top.

**Comment by juan-ortiz92** [comment]
Check is what I did changed the order.

**Comment by Yahid1** [comment]
After review it did not complete the task at hand. This task will be given to a different person.

**Comment by Yahid1** [comment]
If you look at this part of the code it should be easy to understand how to fix this issue. ![Image](https://github.com/user-attachments/assets/87572e2b-9333-4665-acdf-ddaaa47d4f6a)
