### ISSUE TITLE
[Lecture Topic Task] Create a model for the Metrics app

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#81]
Because it would be too convoluted to have one big model that represents the entire system, it would be advised to create multiple individual models. That said, one of the models we could create is one that represents how the Metrics app would function, not only to function as good documentation, but also to give the developers a good idea of what the Metrics app should look like

**Comment by MrL9000** [comment]
Admittedly this one is a bit of a peculiar lecture topic task, but I think it does count, if you'd rather this task be demoted to a doccumentation task I wouldn't mind, I just wanted a good task I know I can start for the start of the milestone

**Comment by MrL9000** [comment]
I have created the model and given it a small description for the readers, notify me once this task has been closed to move it to the Milestone #3 documentation, or if there are any changes I should make. https://docs.google.com/document/d/18b4EzU7qQ1mbOeG5auEbznQBM7TSXiKiuE5KlK5hOCw/edit?tab=t.0

**Comment by Yahid1** [comment]
Its good. Remember this is not necessarily section 4

**Comment by Yahid1** [comment]
When this gets added to the doc I will close this task.

**Comment by MrL9000** [comment]
Added to the doc, 5.14 Specification Pattern. https://docs.google.com/document/d/1cckJSSO8kLDqyC-MK7YW6j686_s-D5HrGuQ3lRCx4xE/edit?tab=t.0

**Comment by gabrielpadilla7** [comment]
closing as completed
