### ISSUE TITLE
Implement Main Menu base code (Metrics Team)

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#83]
Establish a Metrics team branch to ensure order inside the code base

**Comment by Yahid1** [comment]
You can change this Task to something related to the milestone objectives from your team:![Image](https://github.com/user-attachments/assets/20f73761-b2a0-4373-9a75-a5ea23446f10)

**Comment by MrL9000** [comment]
After further deliberation it was decided to make individual branches that would then be merged with main, that said the disscussion that came from this task still means the task was successful in it's goals.
