### ISSUE TITLE
Create a Menu view

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#84]
Take the existing template of the Main Menu, and implement it in the codebase. I will likely also do this task, but it depends on how the team would like to divide the tasks.

**Comment by Yahid1** [comment]
You can change this Task to something related to the milestone objectives from your team: ![Image](https://github.com/user-attachments/assets/f98be318-3524-4c58-9722-cc57dba568a1)

**Comment by MrL9000** [comment]
Pull request has been made in updated the HTML for the main menu of the Vehicle tab

https://github.com/uprm-inso4116-2024-2025-s1/RUMBus-Dashboard/pull/19

**Comment by gabrielpadilla7** [comment]
@MrL9000 Can the Ownerships button and the full data table button be clickable? After the addition of this code, the pages to view the vehicles, the maintenance, devices and the ownership are inaccessible.

**Comment by gabrielpadilla7** [comment]
closing as completed
