### ISSUE TITLE
Ownership View Creation

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#85]

**Comment by marcosarraiza** [comment]
![Image](https://github.com/user-attachments/assets/d8411550-8780-4e03-90ae-153fd808000c)
This is the diagram for what the vehicle ownership page should look like

**Comment by marcosarraiza** [comment]
![Image](https://github.com/user-attachments/assets/b9999b77-76da-4904-9a92-2708495356db)
This is what we created. To navigate to the ownership view, go to the vehicles page first and then click the ownership tab. We had to do this since the menu is still not integrated yet.
