### ISSUE TITLE
Selected Ownership View Creation

### ISSUE THREAD

**Issue by AngelMartinez33** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#86]

**Comment by gabrielpadilla7** [comment]
Please make a pull request on the dashboard code (https://github.com/uprm-inso4116-2024-2025-s1/RUMBus-Dashboard/pulls?q=is%3Aopen+is%3Apr) so we can merge this onto main and we can close this issue. Thank you!

**Comment by Yahid1** [comment]
Looks very good.
