### ISSUE TITLE
Create Tasks for this milestone objective

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#93]
Based on objectives for Milestone #2. Create at least 5 tasks that can be completed for this team.

**Comment by AngelMartinez33** [comment]
Created the following tasks:

- Ownership View Creation
- Selected Ownership View Creation
- Structure of the Vehicles Page
- Revise Vehicles Page Design
- Division of Tasks to Implement Revised Design

**Comment by AngelMartinez33** [comment]
Can someone close this issue? @Yahid1 @gabrielpadilla7

**Comment by gabrielpadilla7** [comment]
Closing as completed
