### ISSUE TITLE
Add Property Numbers 

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#94]
There's an announcement tab that is currently empty. This tab should be filled with the notifications.

**Comment by IvanierB** [comment]
No entiendo muy bien lo que están pidiendo

**Comment by Yahid1** [comment]
It's already done. This task should be changed.

**Comment by IvanierB** [comment]
> It's already done. This task should be changed.

Puedes darme otro task de coding? me hacen falta los puntos

**Comment by Yahid1** [comment]
Yeap

**Comment by Yahid1** [comment]
When theres an active trip this tab should also display the property number of the current vehicle in route.

**Comment by Yahid1** [comment]
![Image](https://github.com/user-attachments/assets/01de616e-9f4e-41ac-852e-fb8200f4e7a9)

The red circle is the active trip data. But we want to add a section where it displays the Property number. 
If you have any question please do not hesitate to ask.

**Comment by Yahid1** [comment]
The blue number is an example of what the property number for each trip would be.

**Comment by Yahid1** [comment]
![Image](https://github.com/user-attachments/assets/cf094d7e-a3b2-4fed-9ffd-69761f2887ec)
It could be done here.

**Comment by IvanierB** [comment]
corrí el main branch y el tab de active trips me sale en blanco

**Comment by Yahid1** [comment]
Es que solo sale cuando hay un trip activo

**Comment by Yahid1** [comment]
Tendrías que agendar un trío para que se ponga activo en el momento de programar

**Comment by IvanierB** [comment]
> Tendrías que agendar un trío para que se ponga activo en el momento de programar 

Lo traté, pero me sale error cuando trato de crear un trip nuevo. Hay algo específico que tenga que poner al crear el trip?

**Comment by Yahid1** [comment]
Yo te enseño ahora

**Comment by Yahid1** [comment]
Estás disponible. Te llame por discord.

**Comment by Janiel777** [comment]
⚠️ **IvanierB** intentó cerrar el issue, pero no tiene permisos para hacerlo. El issue ha sido reabierto.

**Comment by Janiel777** [comment]
⚠️ El usuario **Janiel777** reabrió el issue, pero no tiene permisos. Notificando a @gabrielpadilla7 @Yahid1.

**Comment by IvanierB** [comment]
quería ponerlo en review

**Comment by gabrielpadilla7** [comment]
closing
