### ISSUE TITLE
Encorporate the RUMBus logo

### ISSUE THREAD

**Issue by Yahid1** [uprm-inso4116-2024-2025-s1/semester-project-trolley-tracker-app#96]
Try to incorporate this logo into more visible parts of the application. ![Image](https://github.com/user-attachments/assets/8e8a3c86-506d-4275-bb7c-a53a7058b86e)
This has the effect of making it more friendly and inviting to the User.

**Comment by Yahid1** [comment]
If you need the Original copy. It should be found in this part of the code. ![Image](https://github.com/user-attachments/assets/8715be5b-9375-4511-b49d-5b1a5cfda02e)

**Comment by AngelMartinez33** [comment]
I published a pull request with the addition of the logo in all pages.

**Comment by AngelMartinez33** [comment]
https://github.com/uprm-inso4116-2024-2025-s1/RUMBus-Dashboard/pull/29

**Comment by gabrielpadilla7** [comment]
Closing as completed
